config/routes.rb
Rails.application.routes.draw do
  # get 'books/index'
  # get 'books/show'
  # get 'books/edit'
  # get 'books/new'

  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    validates :name, presence: { message: "Kitap adı boş bırakılamaz!" }
    validates :writer, presence: { message: "Yazar boş bırakılamaz!" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    @book.image.attach(params[:book][:image])
    
    if @book.save
      redirect_to books_path
    else
      render :new
    end

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :description, :writer, :page, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<%= form_with model: @book do |f| %>
    <div class="row mt-50">
        <div class="row mb-3">
            <%= f.label :name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
            </div>
        </div>
        <div class="row mb-3">
            <%= f.label :description, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_area :description, class: "form-control" %>
            </div>
        </div>
        <div class="row mb-3">
            <%= f.label :writer, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_field :writer, class: "form-control" %>
            </div>
        </div>
        <div class="row mb-3">
            <%= f.label :page, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_field :page, class: "form-control" %>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
<% end %>

app/views/books/index.html.erb
<div class="row mt-50">
    <% @books.each do |bk| %>
        <div class="col-md-4 mt-50 mb-50">
            <div class="card-group">
                <div class="card">
                <% if bk.image.attached? %>
                    <%= image_tag bk.image, class: "card-img-top", alt: "Book Image" %>
                <% else %>
                    <p>No image available</p>
                <% end %>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to bk.name, book_path(bk) %> </h5>
                        <p class="card-text"><%= bk.description %></p>
                        <p class="card-text"><small class="text-body-secondary">Writer: <%= bk.writer %></small></p>
                            <%= button_to 'Edit', edit_book_path(bk), class: "btn btn-warning", method: 'get' %>
                            <p></p>
                            <%= button_to 'Remove', book_path(bk), class: "btn btn-danger", method: 'delete', data: {confirm: 'Are you sure?'} %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/books/new.html.erb
<%= form_with model: @book do |f| %>

    <% if @book.errors.any? %>
        <div class="alert alert-danger" role="alert"> 
            <% @book.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>

    <div class="row mt-50">
        <div class="row mb-3">
            <%= f.label :name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
            </div>
        </div>
        <div class="row mb-3">
            <%= f.label :description, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_area :description, class: "form-control" %>
            </div>
        </div>
        <div class="row mb-3">
            <%= f.label :writer, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_field :writer, class: "form-control" %>
            </div>
        </div>
        <div class="row mb-3">
            <%= f.label :page, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.text_field :page, class: "form-control" %>
            </div>
        </div>
        <div class="row mb-3">
            <%= f.label :image, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.file_field :image, class: "form-control" %>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
<% end %>

app/views/books/show.html.erb
<div class="card mb-3 mt-50 mb-50">
    <div class="row g-0">
        <div class="col-md-4">
            <% if @book.image.attached? %>
                    <%= image_tag @book.image, class: "card-img-top", alt: "Book Image" %>
                <% else %>
                    <p>No image available</p>
                <% end %>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><%= @book.name %></h5>
                <p class="card-text"><%= @book.description %></p>
                <p class="card-text"><small class="text-body-secondary">Writer: <%= @book.writer %></small></p>
                <p class="card-text"><small class="text-body-secondary">Pages: <%= @book.page %></small></p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test-Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/books">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/books">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/books/new">Add Book</a>
                </li>
            </ul>
        </div>
    </div>
</nav>